[licenses]
# License requirements
confidence-threshold = 0.8
clarify = [
    { name = "ring", expression = "MIT AND ISC AND OpenSSL", license-files = [] },
]
allow = [
    { allow = ["Apache-2.0", "MIT", "BSD-3-Clause"], confidence-threshold = 0.8 },
]
deny = [
    { deny = ["GPL-1.0", "GPL-2.0", "GPL-3.0", "AGPL-1.0", "AGPL-3.0"], confidence-threshold = 0.8 },
]
exceptions = []

[bans]
# Dependency version requirements
multiple-versions = "warn"
highlight = "all"
skip = [
    # Allow multiple versions of these common dependencies
    { name = "serde" },
    { name = "serde_json" },
]

# Known vulnerability exceptions
skip-tree = [
    # Temporarily allow curve25519-dalek vulnerability until upstream fix
    { name = "curve25519-dalek", version = "=3.2.0" },
]

[sources]
# Source requirements
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"

[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
]

severity-threshold = "medium"

# Temporarily allow known issues
ignore = [
    # curve25519-dalek timing vulnerability - waiting for upstream fix
    "RUSTSEC-2024-0344",
    # derivative unmaintained warning - development dependency
    "RUSTSEC-2024-0388",
] 