name: 'Setup starsd'
description: 'Sets up starsd binary'

inputs:
  branch:
    description: 'Branch to build from'
    required: true
  mnemonic:
    description: 'Mnemonic for the deployer account'
    required: true
  node:
    description: 'RPC endpoint'
    required: false
    default: 'https://rpc.elgafar-1.stargaze-apis.com:443'
  chain_id:
    description: 'Chain ID'
    required: false
    default: 'elgafar-1'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: public-awesome/stargaze
        ref: ${{ inputs.branch }}
        path: stargaze
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache-dependency-path: stargaze/go.sum

    # Cache starsd binary
    - uses: actions/cache@v3
      id: starsd-cache
      with:
        path: ~/go/bin/starsd
        key: ${{ runner.os }}-starsd-${{ inputs.branch }}

    - name: Build starsd
      if: steps.starsd-cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: stargaze
      run: make install

    - name: Configure starsd
      shell: bash
      if: always()
      run: |
        # Configure chain settings
        starsd config set client node ${{ inputs.node }}
        starsd config set client chain-id ${{ inputs.chain_id }}

        # Import deployer key
        echo "${{ inputs.mnemonic }}" | \
          starsd keys add deployer \
          --recover \
          --keyring-backend test
