name: 'Setup Starsd'
description: 'Sets up Starsd environment with caching for Go dependencies'

inputs:
  branch:
    description: 'Branch of Stargaze repository to build from'
    required: false
    default: 'main'
  mnemonic:
    description: 'Mnemonic for the deployment wallet'
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone Stargaze Repository
      uses: actions/checkout@v3
      with:
        repository: public-awesome/stargaze
        ref: ${{ inputs.branch }}
        path: stargaze

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache: true

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles('stargaze/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-

    - name: Build starsd
      shell: bash
      working-directory: stargaze
      run: |
        make install
        echo "PATH=$PATH:$HOME/go/bin" >> $GITHUB_ENV

    - name: Setup wallet
      shell: bash
      run: |
        # Create a temporary file with restricted permissions
        MNEMONIC_FILE=$(mktemp)
        chmod 600 "$MNEMONIC_FILE"
        echo "${{ inputs.mnemonic }}" > "$MNEMONIC_FILE"

        # Import the wallet
        starsd keys add deployer --recover --keyring-backend test < "$MNEMONIC_FILE"

        # Securely remove the mnemonic file
        shred -u "$MNEMONIC_FILE"