---
name: 'Setup Environment'
description: 'Sets up Node.js and Rust environment with caching'

inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: '20'
  rust-version:
    description: 'Rust version'
    required: true
    default: 'stable'
  setup-starsd:
    description: 'Whether to setup starsd CLI'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.rust-version }}
        components: rustfmt, clippy
        targets: wasm32-unknown-unknown

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Setup starsd CLI
      if: inputs.setup-starsd == 'true'
      shell: bash
      run: |
        curl -s https://get.starsd.com | bash
        sudo mv starsd /usr/local/bin/
        starsd version 