name: Contract Compile

on:
  workflow_call:
    inputs:
      contract_name:
        required: true
        type: string
        description: "Name of the contract to compile"
      execution_plan:
        required: true
        type: string
        description: "JSON string containing the execution plan"
    outputs:
      result:
        description: "Result of the workflow (success/failure/skipped)"
        value: ${{ jobs.compile.outputs.result }}
      data:
        description: "JSON string containing all job data"
        value: ${{ jobs.compile.outputs.data }}

jobs:
  compile:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}
      data: ${{ steps.set-result.outputs.data }}
    steps:
      - uses: actions/checkout@v3

      - name: Check previous run
        id: check
        uses: ./.github/actions/check-previous-run
        with:
          execution_plan: ${{ inputs.execution_plan }}
          job_name: compile_${{ inputs.contract_name }}

      - uses: actions-rs/toolchain@v1
        if: steps.check.outputs.result != 'skipped'
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      - name: Compile contract
        id: compile
        if: steps.check.outputs.result != 'skipped'
        run: |
          cd contracts/${{ inputs.contract_name }}
          cargo wasm
          echo "wasm_size=$(du -sh target/wasm32-unknown-unknown/release/*.wasm | cut -f1)" >> $GITHUB_OUTPUT
          echo "rust_version=$(rustc --version)" >> $GITHUB_OUTPUT

      - name: Set result
        id: set-result
        if: always()
        run: |
          if [[ "${{ steps.check.outputs.result }}" == "skipped" ]]; then
            echo "data=${{ steps.check.outputs.data }}" >> $GITHUB_OUTPUT
            echo "result=skipped" >> $GITHUB_OUTPUT
          else
            echo "result=${{ job.status }}" >> $GITHUB_OUTPUT
            echo "data=$(jq -n \
              --arg size "${{ steps.compile.outputs.wasm_size }}" \
              --arg ver "${{ steps.compile.outputs.rust_version }}" \
              '{wasm_size: $size, rust_version: $ver}')" >> $GITHUB_OUTPUT
          fi 