name: Contract Format

on:
  workflow_call:
    inputs:
      contract_name:
        required: true
        type: string
        description: "Name of the contract to format check"
      execution_plan:
        required: true
        type: string
        description: "JSON string containing the execution plan"
    outputs:
      result:
        description: "Result of the workflow (success/failure/skipped)"
        value: ${{ jobs.fmt.outputs.result }}
      data:
        description: "JSON string containing all job data"
        value: ${{ jobs.fmt.outputs.data }}

jobs:
  fmt:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}
      data: ${{ steps.set-result.outputs.data }}
    steps:
      - uses: actions/checkout@v3

      - name: Check previous run
        id: check
        uses: ./.github/actions/check-previous-run
        with:
          execution_plan: ${{ inputs.execution_plan }}
          job_name: fmt_${{ inputs.contract_name }}

      - name: Setup environment
        if: steps.check.outputs.result != 'skipped'
        uses: ./.github/actions/setup-env
        with:
          node-version: '20'  # For tooling scripts
          rust-version: stable

      - name: Run rustfmt
        id: fmt
        if: steps.check.outputs.result != 'skipped'
        run: |
          cd contracts/${{ inputs.contract_name }}
          cargo fmt --all -- --check
          echo "fmt_version=$(cargo fmt --version)" >> $GITHUB_OUTPUT

      - name: Set result
        id: set-result
        if: always()
        run: |
          if [[ "${{ steps.check.outputs.result }}" == "skipped" ]]; then
            echo "data=${{ steps.check.outputs.data }}" >> $GITHUB_OUTPUT
            echo "result=skipped" >> $GITHUB_OUTPUT
          else
            echo "result=${{ job.status }}" >> $GITHUB_OUTPUT
            echo "data=$(jq -n \
              --arg ver "${{ steps.fmt.outputs.fmt_version }}" \
              '{fmt_version: $ver}')" >> $GITHUB_OUTPUT
          fi 