name: Contract Compile

on:
  workflow_call:
    inputs:
      contract_name:
        required: true
        type: string
        description: "Name of the contract to compile"
      execution_plan:
        required: true
        type: string
        description: "JSON string containing the execution plan"
    outputs:
      result:
        description: "Result of the workflow (success/failure/skipped)"
        value: ${{ jobs.compile.outputs.result }}
      data:
        description: "JSON string containing all job data"
        value: ${{ jobs.compile.outputs.data }}

jobs:
  compile:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}
      data: ${{ steps.set-result.outputs.data }}
    steps:
      - uses: actions/checkout@v3

      - name: Check previous run
        id: check
        uses: ./.github/actions/check-previous-run
        with:
          execution_plan: ${{ inputs.execution_plan }}
          job_name: compile_${{ inputs.contract_name }}

      - uses: dtolnay/rust-toolchain@stable
        if: steps.check.outputs.result != 'skipped'
        with:
          toolchain: stable
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown

      - name: Cache Rust dependencies
        if: steps.check.outputs.result != 'skipped'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('contracts/Cargo.toml') }}-${{ hashFiles(format('contracts/{0}/Cargo.toml', inputs.contract_name)) }}

      - name: Compile contract
        id: compile
        if: steps.check.outputs.result != 'skipped'
        working-directory: contracts
        run: |
          cargo build --target wasm32-unknown-unknown --release --package ${{ inputs.contract_name }}
          mkdir -p ${{ inputs.contract_name }}/artifacts
          cp target/wasm32-unknown-unknown/release/${{ inputs.contract_name }}.wasm ${{ inputs.contract_name }}/artifacts/
          echo "wasm_path=${{ inputs.contract_name }}/artifacts/${{ inputs.contract_name }}.wasm" >> $GITHUB_OUTPUT

      - name: Upload WASM artifact
        if: steps.check.outputs.result != 'skipped'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.contract_name }}-wasm
          path: contracts/${{ inputs.contract_name }}/artifacts/${{ inputs.contract_name }}.wasm
          retention-days: 1
      
      - name: Set result
        id: set-result
        if: always()
        uses: ./.github/actions/set-result
        with:
          previous_run_result: ${{ steps.check.outputs.result }}
          previous_run_data: ${{ steps.check.outputs.data }}
          job_status: ${{ job.status }}
          job_data: ${{ '{}' }}