name: Contract Clippy

on:
  workflow_call:
    inputs:
      contract_name:
        required: true
        type: string
        description: "Name of the contract to lint with clippy"
      execution_plan:
        required: true
        type: string
        description: "JSON string containing the execution plan"
    outputs:
      result:
        description: "Result of the workflow (success/failure/skipped)"
        value: ${{ jobs.clippy.outputs.result }}
      data:
        description: "JSON string containing all job data"
        value: ${{ jobs.clippy.outputs.data }}

jobs:
  clippy:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}
      data: ${{ steps.set-result.outputs.data }}
    steps:
      - uses: actions/checkout@v3

      - name: Check previous run
        id: check
        uses: ./.github/actions/check-previous-run
        with:
          execution_plan: ${{ inputs.execution_plan }}
          job_name: ${{ inputs.contract_name }}_clippy

      - uses: dtolnay/rust-toolchain@stable
        if: steps.check.outputs.result != 'skipped'
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        if: steps.check.outputs.result != 'skipped'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('contracts/Cargo.toml') }}-${{ hashFiles(format('contracts/{0}/Cargo.toml', inputs.contract_name)) }}

      - name: Run clippy
        id: clippy
        if: steps.check.outputs.result != 'skipped'
        run: |
          cd contracts/${{ inputs.contract_name }}
          cargo clippy -- -D warnings

      - name: Set result
        id: set-result
        if: always()
        uses: ./.github/actions/set-result
        with:
          previous_run_result: ${{ steps.check.outputs.result }}
          previous_run_data: ${{ steps.check.outputs.data }}
          job_status: ${{ job.status }}
          job_data: ${{ '{}' }}