name: E2E Tests

on:
  workflow_call:
    inputs:
      test_type:
        required: true
        type: string
        description: "Type of E2E test to run (mosaic-tile/mosaic-vending/full)"
      execution_plan:
        required: true
        type: string
        description: "JSON string containing the execution plan"
      contract_address:
        required: true
        type: string
        description: "Address of the deployed contract to test" 
    secrets:
      DEPLOYER_MNEMONIC:
        required: true
        description: "Mnemonic for the deployer account"
      MINTER_MNEMONIC:
        required: true
        description: "Mnemonic for the minter account"
      OWNER_MNEMONIC:
        required: true
        description: "Mnemonic for the owner account"
      USER_MNEMONIC:
        required: true
        description: "Mnemonic for the user account"
    outputs:
      result:
        description: "Result of the workflow (success/failure/skipped)"
        value: ${{ jobs.e2e.outputs.result }}
      data:
        description: "JSON string containing all job data"
        value: ${{ jobs.e2e.outputs.data }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}
      data: ${{ steps.set-result.outputs.data }}
    steps:
      - uses: actions/checkout@v3

      - name: Check previous run
        id: check
        uses: ./.github/actions/check-previous-run
        with:
          execution_plan: ${{ inputs.execution_plan }}
          job_name: ${{ inputs.test_type }}_e2e

      - name: Setup starsd
        id: setup-starsd
        if: steps.check.outputs.result != 'skipped'
        uses: ./.github/actions/setup-starsd
        with:
          branch: v14.0.0
          deployer_mnemonic: ${{ secrets.DEPLOYER_MNEMONIC }}
          minter_mnemonic: ${{ secrets.MINTER_MNEMONIC }}
          owner_mnemonic: ${{ secrets.OWNER_MNEMONIC }}
          user_mnemonic: ${{ secrets.USER_MNEMONIC }}
        
      - name: Setup Rust
        if: steps.check.outputs.result != 'skipped' && inputs.test_type == 'mosaic-tile'
        uses: ./.github/actions/setup-rust
        
      - name: Run Mosaic Tile E2E Tests
        if: steps.check.outputs.result != 'skipped' && inputs.test_type == 'mosaic-tile'
        working-directory: contracts/mosaic_tile_nft
        env:
          CONTRACT_ADDRESS: ${{ steps.setup-starsd.outputs.contract_address }}
          DEPLOYER_ADDRESS: ${{ steps.setup-starsd.outputs.deployer_address }}
          MINTER_ADDRESS: ${{ steps.setup-starsd.outputs.minter_address }}
          OWNER_ADDRESS: ${{ steps.setup-starsd.outputs.owner_address }}
          USER_ADDRESS: ${{ steps.setup-starsd.outputs.user_address }}
        run: |
          cargo test --test e2e -- --nocapture

      - name: Mock Mosaic Vending E2E Tests
        if: steps.check.outputs.result != 'skipped' && inputs.test_type == 'mosaic-vending'
        run: |
          echo "Mosaic Vending E2E tests are currently disabled"

      - name: Mock Full E2E Tests
        if: steps.check.outputs.result != 'skipped' && inputs.test_type == 'full'
        run: |
          echo "Full E2E tests are currently disabled"

      - name: Set result
        id: set-result
        if: always()
        uses: ./.github/actions/set-result
        with:
          previous_run_result: ${{ steps.check.outputs.result }}
          previous_run_data: ${{ steps.check.outputs.data }}
          job_status: ${{ job.status }}
          job_data: '{}'