name: Frontend Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

env:
  NEXT_PUBLIC_STARGAZE_TESTNET_RPC: "https://rpc.elgafar-1.stargaze-apis.com"
  NEXT_PUBLIC_STARGAZE_TESTNET_CHAIN_ID: "elgafar-1"
  NEXT_PUBLIC_CONTRACT_ADDRESS: ${{ secrets.TESTNET_CONTRACT_ADDRESS }}

jobs:
  test:
    name: Frontend Test Suite
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Check TypeScript
        working-directory: ./frontend
        run: npm run type-check

      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint

      - name: Run unit tests
        working-directory: ./frontend
        run: npm run test

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          directory: ./frontend/coverage

  e2e:
    name: E2E Tests
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install Playwright browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps chromium

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Start frontend and run tests
        working-directory: ./frontend
        run: |
          npm start &
          sleep 10
          npx playwright test --project=chromium
        env:
          NEXT_PUBLIC_STARGAZE_TESTNET_RPC: ${{ env.NEXT_PUBLIC_STARGAZE_TESTNET_RPC }}
          NEXT_PUBLIC_STARGAZE_TESTNET_CHAIN_ID: ${{ env.NEXT_PUBLIC_STARGAZE_TESTNET_CHAIN_ID }}
          NEXT_PUBLIC_CONTRACT_ADDRESS: ${{ env.NEXT_PUBLIC_CONTRACT_ADDRESS }}
          TESTNET_MNEMONIC: ${{ secrets.TESTNET_MNEMONIC }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30

      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-screenshots
          path: frontend/test-results/
          retention-days: 7