name: Frontend Lint

on:
  workflow_call:
    inputs:
      execution_plan:
        required: true
        type: string
        description: "JSON string containing the execution plan"
    outputs:
      result:
        description: "Result of the workflow (success/failure/skipped)"
        value: ${{ jobs.lint.outputs.result }}
      data:
        description: "JSON string containing all job data"
        value: ${{ jobs.lint.outputs.data }}

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}
      data: ${{ steps.set-result.outputs.data }}
    steps:
      - uses: actions/checkout@v3

      - name: Check previous run
        id: check
        uses: ./.github/actions/check-previous-run
        with:
          execution_plan: ${{ inputs.execution_plan }}
          job_name: frontend_lint

      - name: Setup Node.js environment
        if: steps.check.outputs.result != 'skipped'
        uses: ./.github/actions/setup-node
        with:
          working-directory: frontend
          node-version: '20'

      - name: Run lint
        id: lint
        if: steps.check.outputs.result != 'skipped'
        working-directory: frontend
        run: |
          npm run lint

      - name: Set result
        id: set-result
        if: always()
        uses: ./.github/actions/set-result
        with:
          previous_run_result: ${{ steps.check.outputs.result }}
          previous_run_data: ${{ steps.check.outputs.data }}
          job_status: ${{ job.status }}
          job_data: ${{ '{}' }}