name: Frontend Lint

on:
  workflow_call:
    inputs:
      execution_plan:
        required: true
        type: string
        description: "JSON string containing the execution plan"
    outputs:
      result:
        description: "Result of the workflow (success/failure/skipped)"
        value: ${{ jobs.lint.outputs.result }}
      data:
        description: "JSON string containing all job data"
        value: ${{ jobs.lint.outputs.data }}

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}
      data: ${{ steps.set-result.outputs.data }}
    steps:
      - uses: actions/checkout@v3

      - name: Check previous run
        id: check
        uses: ./.github/actions/check-previous-run
        with:
          execution_plan: ${{ inputs.execution_plan }}
          job_name: frontend_ci_lint

      - name: Setup environment
        if: steps.check.outputs.result != 'skipped'
        uses: ./.github/actions/setup-env
        with:
          node-version: '20'
          node-cache-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        if: steps.check.outputs.result != 'skipped'
        run: |
          npm ci

      - name: Run lint
        id: lint
        working-directory: frontend
        if: steps.check.outputs.result != 'skipped'
        run: |
          npm run lint
          echo "eslint_version=$(npm list eslint | head -n1)" >> $GITHUB_OUTPUT

      - name: Set result
        id: set-result
        if: always()
        run: |
          if [[ "${{ steps.check.outputs.result }}" == "skipped" ]]; then
            echo "data=${{ steps.check.outputs.data }}" >> $GITHUB_OUTPUT
            echo "result=skipped" >> $GITHUB_OUTPUT
          else
            echo "result=${{ job.status }}" >> $GITHUB_OUTPUT
          fi 