name: Mosaic CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: read
  contents: read
  actions: read

jobs:
  execution_plan:
    uses: ./.github/workflows/reusable-execution-plan.yml
    with:
      GIST_ID: ${{ vars.GIST_ID }}
      GITHUB_SHA: ${{ github.sha }}
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}

  rust_setup:
    uses: ./.github/workflows/reusable-rust-setup.yml

  frontend_ci:
    needs: execution_plan
    uses: ./.github/workflows/reusable-frontend.yml
    with:
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['frontend_ci_lint'].needs_run }}
      component_hash: ${{ fromJson(needs.execution_plan.outputs.plan).components.frontend }}

  mosaic_tile_ci:
    needs: [execution_plan, rust_setup]
    uses: ./.github/workflows/reusable-contracts.yml
    with:
      contract_name: mosaic-tile-nft
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['mosaic_tile_ci_format'].needs_run }}
      component_hash: ${{ fromJson(needs.execution_plan.outputs.plan).components.mosaic_tile }}

  mosaic_vending_ci:
    needs: [execution_plan, rust_setup]
    uses: ./.github/workflows/reusable-contracts.yml
    with:
      contract_name: mosaic-vending-minter
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['mosaic_vending_ci_format'].needs_run }}
      component_hash: ${{ fromJson(needs.execution_plan.outputs.plan).components.mosaic_vending }}

  deploy_mosaic_tile:
    needs: [execution_plan, mosaic_tile_ci]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      contract_name: mosaic-tile-nft
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['deploy_mosaic_tile'].needs_run }}
      code_id: ${{ needs.mosaic_tile_ci.outputs.code_id }}
      contract_address: ${{ needs.mosaic_tile_ci.outputs.contract_address }}
      component_hash: ${{ fromJson(needs.execution_plan.outputs.plan).components.mosaic_tile }}
    secrets:
      STARSD_MNEMONIC: ${{ secrets.DEPLOYMENT_WALLET_MNEMONIC }}

  deploy_mosaic_vending:
    needs: [execution_plan, mosaic_vending_ci]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      contract_name: mosaic-vending-minter
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['deploy_mosaic_vending'].needs_run }}
      code_id: ${{ needs.mosaic_vending_ci.outputs.code_id }}
      contract_address: ${{ needs.mosaic_vending_ci.outputs.contract_address }}
      component_hash: ${{ fromJson(needs.execution_plan.outputs.plan).components.mosaic_vending }}
    secrets:
      STARSD_MNEMONIC: ${{ secrets.DEPLOYMENT_WALLET_MNEMONIC }}

  mosaic_tile_e2e:
    needs: [execution_plan, deploy_mosaic_tile]
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      test_type: mosaic-tile
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['mosaic_tile_e2e'].needs_run }}

  mosaic_vending_e2e:
    needs: [execution_plan, deploy_mosaic_vending]
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      test_type: mosaic-vending
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['mosaic_vending_e2e'].needs_run }}

  full_e2e:
    needs: [execution_plan, frontend_ci, mosaic_tile_e2e, mosaic_vending_e2e]
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      test_type: full
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['full_e2e'].needs_run }}

  notify:
    needs: [execution_plan, frontend_ci, mosaic_tile_ci, mosaic_vending_ci, deploy_mosaic_tile, deploy_mosaic_vending, mosaic_tile_e2e, mosaic_vending_e2e, full_e2e]
    if: always()
    uses: ./.github/workflows/reusable-notify.yml
    with:
      execution_plan: ${{ needs.execution_plan.outputs.plan }}
      frontend_lint_result: ${{ needs.frontend_ci.outputs.lint_result }}
      frontend_test_result: ${{ needs.frontend_ci.outputs.test_result }}
      frontend_build_result: ${{ needs.frontend_ci.outputs.build_result }}
      mosaic_tile_format_result: ${{ needs.mosaic_tile_ci.outputs.format_result }}
      mosaic_tile_lint_result: ${{ needs.mosaic_tile_ci.outputs.lint_result }}
      mosaic_tile_test_result: ${{ needs.mosaic_tile_ci.outputs.test_result }}
      mosaic_tile_schema_result: ${{ needs.mosaic_tile_ci.outputs.schema_result }}
      mosaic_tile_deploy_result: ${{ needs.deploy_mosaic_tile.outputs.result }}
      mosaic_tile_deploy_code_id: ${{ needs.deploy_mosaic_tile.outputs.code_id }}
      mosaic_tile_deploy_contract_address: ${{ needs.deploy_mosaic_tile.outputs.contract_address }}
      mosaic_tile_e2e_result: ${{ needs.mosaic_tile_e2e.outputs.e2e_result }}
      mosaic_vending_format_result: ${{ needs.mosaic_vending_ci.outputs.format_result }}
      mosaic_vending_lint_result: ${{ needs.mosaic_vending_ci.outputs.lint_result }}
      mosaic_vending_test_result: ${{ needs.mosaic_vending_ci.outputs.test_result }}
      mosaic_vending_schema_result: ${{ needs.mosaic_vending_ci.outputs.schema_result }}
      mosaic_vending_deploy_result: ${{ needs.deploy_mosaic_vending.outputs.result }}
      mosaic_vending_deploy_code_id: ${{ needs.deploy_mosaic_vending.outputs.code_id }}
      mosaic_vending_deploy_contract_address: ${{ needs.deploy_mosaic_vending.outputs.contract_address }}
      mosaic_vending_e2e_result: ${{ needs.mosaic_vending_e2e.outputs.e2e_result }}
      full_e2e_result: ${{ needs.full_e2e.outputs.e2e_result }}
      gist_id: ${{ vars.GIST_ID }}
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
