name: Mosaic CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: read
  contents: read
  actions: read

jobs:
  execution_plan:
    uses: ./.github/workflows/reusable-execution-plan.yml
    with:
      GIST_ID: ${{ vars.GIST_ID }}
      GITHUB_SHA: ${{ github.sha }}
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}

  rust-setup:
    uses: ./.github/workflows/reusable-rust-setup.yml

  frontend-ci:
    needs: execution_plan
    uses: ./.github/workflows/reusable-frontend.yml
    with:
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['frontend-ci-lint'].needs_run }}
      component_hash: ${{ fromJson(needs.execution_plan.outputs.plan).components.frontend }}

  mosaic-tile-ci:
    needs: [execution_plan, rust-setup]
    uses: ./.github/workflows/reusable-contracts.yml
    with:
      contract_name: mosaic-tile-nft
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['mosaic-tile-ci-format'].needs_run }}
      component_hash: ${{ fromJson(needs.execution_plan.outputs.plan).components.mosaic_tile }}

  mosaic-vending-ci:
    needs: [execution_plan, rust-setup]
    uses: ./.github/workflows/reusable-contracts.yml
    with:
      contract_name: mosaic-vending-minter
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['mosaic-vending-ci-format'].needs_run }}
      component_hash: ${{ fromJson(needs.execution_plan.outputs.plan).components.mosaic_vending }}

  deploy-mosaic-tile:
    needs: [execution_plan, mosaic-tile-ci]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      contract_name: mosaic-tile-nft
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['deploy-mosaic-tile'].needs_run }}
      code_id: ${{ needs.mosaic-tile-ci.outputs.code_id }}
      contract_address: ${{ needs.mosaic-tile-ci.outputs.contract_address }}
      component_hash: ${{ fromJson(needs.execution_plan.outputs.plan).components.mosaic_tile }}
    secrets:
      STARSD_MNEMONIC: ${{ secrets.STARSD_MNEMONIC }}

  deploy-mosaic-vending:
    needs: [execution_plan, mosaic-vending-ci]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      contract_name: mosaic-vending-minter
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['deploy-mosaic-vending'].needs_run }}
      component_hash: ${{ fromJson(needs.execution_plan.outputs.plan).components.mosaic_vending }}
    secrets:
      STARSD_MNEMONIC: ${{ secrets.STARSD_MNEMONIC }}

  mosaic-tile-e2e:
    needs: deploy-mosaic-tile
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      test_type: mosaic-tile
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['mosaic-tile-e2e'].needs_run }}

  mosaic-vending-e2e:
    needs: deploy-mosaic-vending
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      test_type: mosaic-vending
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['mosaic-vending-e2e'].needs_run }}

  full-e2e:
    needs: [frontend-ci, mosaic-tile-e2e, mosaic-vending-e2e]
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      test_type: full
      needs_run: ${{ fromJson(needs.execution_plan.outputs.plan).jobs['full-e2e'].needs_run }}

  notify:
    needs: [execution_plan, frontend-ci, mosaic-tile-ci, mosaic-vending-ci, deploy-mosaic-tile, deploy-mosaic-vending, mosaic-tile-e2e, mosaic-vending-e2e, full-e2e]
    if: always()
    uses: ./.github/workflows/reusable-notify.yml
    with:
      execution_plan: ${{ needs.execution_plan.outputs.plan }}
      frontend_lint_result: ${{ needs.frontend-ci.outputs.lint_result }}
      frontend_test_result: ${{ needs.frontend-ci.outputs.test_result }}
      frontend_build_result: ${{ needs.frontend-ci.outputs.build_result }}
      mosaic_tile_format_result: ${{ needs.mosaic-tile-ci.outputs.format_result }}
      mosaic_tile_lint_result: ${{ needs.mosaic-tile-ci.outputs.lint_result }}
      mosaic_tile_test_result: ${{ needs.mosaic-tile-ci.outputs.test_result }}
      mosaic_tile_schema_result: ${{ needs.mosaic-tile-ci.outputs.schema_result }}
      mosaic_tile_deploy_result: ${{ needs.deploy-mosaic-tile.outputs.result }}
      mosaic_tile_deploy_code_id: ${{ needs.deploy-mosaic-tile.outputs.code_id }}
      mosaic_tile_deploy_contract_address: ${{ needs.deploy-mosaic-tile.outputs.contract_address }}
      mosaic_tile_e2e_result: ${{ needs.mosaic-tile-e2e.outputs.e2e_result }}
      mosaic_vending_format_result: ${{ needs.mosaic-vending-ci.outputs.format_result }}
      mosaic_vending_lint_result: ${{ needs.mosaic-vending-ci.outputs.lint_result }}
      mosaic_vending_test_result: ${{ needs.mosaic-vending-ci.outputs.test_result }}
      mosaic_vending_schema_result: ${{ needs.mosaic-vending-ci.outputs.schema_result }}
      mosaic_vending_deploy_result: ${{ needs.deploy-mosaic-vending.outputs.result }}
      mosaic_vending_deploy_code_id: ${{ needs.deploy-mosaic-vending.outputs.code_id }}
      mosaic_vending_deploy_contract_address: ${{ needs.deploy-mosaic-vending.outputs.contract_address }}
      mosaic_vending_e2e_result: ${{ needs.mosaic-vending-e2e.outputs.e2e_result }}
      full_e2e_result: ${{ needs.full-e2e.outputs.e2e_result }}
      gist_id: ${{ vars.GIST_ID }}
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
