name: Mosaic CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: read
  contents: read
  actions: read

jobs:
  execution-plan:
    uses: ./.github/workflows/reusable-execution-plan.yml
    with:
      gist_id: ${{ vars.GIST_ID }}
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}

  rust-setup:
    uses: ./.github/workflows/reusable-rust-setup.yml

  frontend-ci:
    needs: execution-plan
    uses: ./.github/workflows/reusable-frontend.yml
    with:
      needs_run: ${{ fromJson(needs.execution-plan.outputs.plan).jobs.frontend-ci.needs_run }}
      component_hash: ${{ fromJson(needs.execution-plan.outputs.plan).components.frontend.hash }}

  mosaic-tile-ci:
    needs: [execution-plan, rust-setup]
    uses: ./.github/workflows/reusable-contracts.yml
    with:
      contract_name: mosaic-tile-nft
      needs_run: ${{ fromJson(needs.execution-plan.outputs.plan).jobs.mosaic-tile-ci.needs_run }}
      component_hash: ${{ fromJson(needs.execution-plan.outputs.plan).components.mosaic_tile.hash }}

  mosaic-vending-ci:
    needs: [execution-plan, rust-setup]
    uses: ./.github/workflows/reusable-contracts.yml
    with:
      contract_name: mosaic-vending-minter
      needs_run: ${{ fromJson(needs.execution-plan.outputs.plan).jobs.mosaic-vending-ci.needs_run }}
      component_hash: ${{ fromJson(needs.execution-plan.outputs.plan).components.mosaic_vending.hash }}

  deploy-mosaic-tile:
    needs: mosaic-tile-ci
    if: needs.mosaic-tile-ci.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy mosaic-tile contract
        run: echo "Deploying mosaic-tile contract..."

  deploy-mosaic-vending:
    needs: mosaic-vending-ci
    if: needs.mosaic-vending-ci.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy mosaic-vending contract
        run: echo "Deploying mosaic-vending contract..."

  mosaic-tile-e2e:
    needs: deploy-mosaic-tile
    if: needs.deploy-mosaic-tile.result == 'success'
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      test_type: mosaic-tile
      needs_run: ${{ fromJson(needs.execution-plan.outputs.plan).jobs.mosaic-tile-e2e.needs_run }}

  mosaic-vending-e2e:
    needs: deploy-mosaic-vending
    if: needs.deploy-mosaic-vending.result == 'success'
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      test_type: mosaic-vending
      needs_run: ${{ fromJson(needs.execution-plan.outputs.plan).jobs.mosaic-vending-e2e.needs_run }}

  full-e2e:
    needs: [frontend-ci, mosaic-tile-e2e, mosaic-vending-e2e]
    if: |
      needs.frontend-ci.result == 'success' && 
      needs.mosaic-tile-e2e.result == 'success' && 
      needs.mosaic-vending-e2e.result == 'success'
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      test_type: full
      needs_run: ${{ fromJson(needs.execution-plan.outputs.plan).jobs.full-e2e.needs_run }}

  notify:
    needs: [execution-plan, frontend-ci, mosaic-tile-ci, mosaic-vending-ci, deploy-mosaic-tile, deploy-mosaic-vending, mosaic-tile-e2e, mosaic-vending-e2e, full-e2e]
    if: always()
    uses: ./.github/workflows/reusable-notify.yml
    with:
      execution_plan: ${{ needs.execution-plan.outputs.plan }}
      frontend_ci_result: ${{ needs.frontend-ci.result }}
      mosaic_tile_ci_result: ${{ needs.mosaic-tile-ci.result }}
      mosaic_vending_ci_result: ${{ needs.mosaic-vending-ci.result }}
      mosaic_tile_deploy_result: ${{ needs.deploy-mosaic-tile.result }}
      mosaic_vending_deploy_result: ${{ needs.deploy-mosaic-vending.result }}
      mosaic_tile_e2e_result: ${{ needs.mosaic-tile-e2e.result }}
      mosaic_vending_e2e_result: ${{ needs.mosaic-vending-e2e.result }}
      full_e2e_result: ${{ needs.full-e2e.result }}
      gist_id: ${{ vars.GIST_ID }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
