name: Changes Detection

on:
  workflow_call:
    outputs:
      frontend_needs_run:
        description: "Whether frontend CI needs to run"
        value: ${{ jobs.check-needs-run.outputs.frontend_needs_run }}
      mosaic_tile_needs_run:
        description: "Whether mosaic-tile CI needs to run"
        value: ${{ jobs.check-needs-run.outputs.mosaic_tile_needs_run }}
      mosaic_vending_needs_run:
        description: "Whether mosaic-vending CI needs to run"
        value: ${{ jobs.check-needs-run.outputs.mosaic_vending_needs_run }}
      full_e2e_needs_run:
        description: "Whether full E2E tests need to run"
        value: ${{ jobs.check-needs-run.outputs.full_e2e_needs_run }}
      frontend_hash:
        description: "Hash of frontend changes"
        value: ${{ jobs.generate-hashes.outputs.frontend_hash }}
      mosaic_tile_hash:
        description: "Hash of mosaic-tile changes"
        value: ${{ jobs.generate-hashes.outputs.mosaic_tile_hash }}
      mosaic_vending_hash:
        description: "Hash of mosaic-vending changes"
        value: ${{ jobs.generate-hashes.outputs.mosaic_vending_hash }}

jobs:
  # Job 1: Check which paths have changed
  check-paths:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      mosaic_tile: ${{ steps.filter.outputs.mosaic_tile }}
      mosaic_vending: ${{ steps.filter.outputs.mosaic_vending }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            mosaic_tile:
              - 'contracts/mosaic-tile-nft/**'
              - 'contracts/Cargo.toml'
            mosaic_vending:
              - 'contracts/mosaic-vending-minter/**'
              - 'contracts/Cargo.toml'

  # Job 2: Generate component hashes (can run in parallel with check-paths)
  generate-hashes:
    runs-on: ubuntu-latest
    outputs:
      frontend_hash: ${{ steps.hashes.outputs.frontend_hash }}
      mosaic_tile_hash: ${{ steps.hashes.outputs.mosaic_tile_hash }}
      mosaic_vending_hash: ${{ steps.hashes.outputs.mosaic_vending_hash }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Generate component hashes
        id: hashes
        run: |
          # Frontend hash
          if [[ -d "frontend" ]]; then
            frontend_hash=$(find frontend -type f -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1)
          else
            frontend_hash="empty_directory"
          fi
          echo "frontend_hash=$frontend_hash" >> $GITHUB_OUTPUT

          # Mosaic tile hash
          if [[ -d "contracts/mosaic-tile-nft" ]]; then
            mosaic_tile_hash=$(find contracts/mosaic-tile-nft -type f -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1)
          else
            mosaic_tile_hash="empty_directory"
          fi
          echo "mosaic_tile_hash=$mosaic_tile_hash" >> $GITHUB_OUTPUT

          # Mosaic vending hash
          if [[ -d "contracts/mosaic-vending-minter" ]]; then
            mosaic_vending_hash=$(find contracts/mosaic-vending-minter -type f -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1)
          else
            mosaic_vending_hash="empty_directory"
          fi
          echo "mosaic_vending_hash=$mosaic_vending_hash" >> $GITHUB_OUTPUT

  # Job 3: Check previous runs (depends on both check-paths and generate-hashes)
  check-needs-run:
    needs: [check-paths, generate-hashes]
    runs-on: ubuntu-latest
    permissions:
      actions: read
    outputs:
      frontend_needs_run: ${{ steps.check-runs.outputs.frontend_needs_run }}
      mosaic_tile_needs_run: ${{ steps.check-runs.outputs.mosaic_tile_needs_run }}
      mosaic_vending_needs_run: ${{ steps.check-runs.outputs.mosaic_vending_needs_run }}
      full_e2e_needs_run: ${{ steps.check-runs.outputs.full_e2e_needs_run }}
    steps:
      - name: Check if jobs need to run
        id: check-runs
        env:
          GH_TOKEN: ${{ github.token }}
          FRONTEND_HASH: ${{ needs.generate-hashes.outputs.frontend_hash }}
          MOSAIC_TILE_HASH: ${{ needs.generate-hashes.outputs.mosaic_tile_hash }}
          MOSAIC_VENDING_HASH: ${{ needs.generate-hashes.outputs.mosaic_vending_hash }}
        run: |
          # Function to check if a job needs to run
          check_job_needs_run() {
            local job_name=$1
            local component_hash=$2
            
            # Look for a successful run with this exact hash
            local last_successful_run_with_hash=$(gh run list --workflow pixel-canvas.yml \
              --json conclusion,jobs,databaseId \
              --jq ".[] | select(.jobs[].name == \"$job_name\" and .conclusion == \"success\")" \
              --limit 10 | while read -r run; do
                run_id=$(echo "$run" | jq -r '.databaseId')
                run_hash=$(gh api "/repos/${{ github.repository }}/actions/runs/$run_id/jobs" \
                  --jq ".jobs[] | select(.name == \"check-needs-run\").steps[] | select(.name == \"Check if jobs need to run\").outputs.${component_hash}")
                
                if [[ "$run_hash" == "${!component_hash}" ]]; then
                  echo "found"
                  break
                fi
              done)
            
            # If we found a successful run with this hash, we can skip
            if [[ -n "$last_successful_run_with_hash" ]]; then
              echo "false"
            else
              echo "true"
            fi
          }
          
          # Check each job
          echo "frontend_needs_run=$(check_job_needs_run "frontend-ci" "FRONTEND_HASH")" >> $GITHUB_OUTPUT
          echo "mosaic_tile_needs_run=$(check_job_needs_run "mosaic-tile-ci" "MOSAIC_TILE_HASH")" >> $GITHUB_OUTPUT
          echo "mosaic_vending_needs_run=$(check_job_needs_run "mosaic-vending-ci" "MOSAIC_VENDING_HASH")" >> $GITHUB_OUTPUT
          
          # Full E2E needs to run if any component changed
          if [[ "${{ needs.check-paths.outputs.frontend }}" == "true" || \
                "${{ needs.check-paths.outputs.mosaic_tile }}" == "true" || \
                "${{ needs.check-paths.outputs.mosaic_vending }}" == "true" ]]; then
            echo "full_e2e_needs_run=true" >> $GITHUB_OUTPUT
          else
            echo "full_e2e_needs_run=false" >> $GITHUB_OUTPUT
          fi 