name: Generate Execution Plan

on:
  workflow_call:
    inputs:
      GIST_ID:
        required: true
        type: string
        description: "Gist ID for storing job results"
      GITHUB_SHA:
        required: true
        type: string
        description: "Github SHA for the current commit"
    secrets:
      GIST_SECRET:
        required: true
        description: "Token for gist access"
    outputs:
      plan:
        description: "Complete execution plan for all jobs"
        value: ${{ jobs.create-plan.outputs.plan }}

permissions:
  contents: read
  actions: read

jobs:
  create-plan:
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.plan.outputs.plan }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: .github/workflow-scripts/package.json

      - name: Install dependencies
        working-directory: .github/workflow-scripts
        run: npm ci

      - name: Generate execution plan
        id: plan
        env:
          GIST_SECRET: ${{ secrets.GIST_SECRET }}
          GIST_ID: ${{ inputs.GIST_ID }}
          GITHUB_SHA: ${{ inputs.GITHUB_SHA }}
        run: |
          cd .github/workflow-scripts
          npm run execution-plan
          # Escape newlines and quotes
          PLAN=$(cat execution-plan.json | jq -c .)
          echo "plan=${PLAN}" >> $GITHUB_OUTPUT
