name: Status Management

on:
  workflow_call:
    inputs:
      action:
        required: true
        type: string
        description: "Action to perform: 'read' or 'update'"
      component_hash:
        required: false
        type: string
        description: "Hash of the component to look up"
      component_name:
        required: false
        type: string
        description: "Name of the component (frontend, mosaic_tile, mosaic_vending)"
      execution_plan:
        required: false
        type: string
        description: "Current execution plan to store"
      gist_id:
        required: true
        type: string
    secrets:
      GIST_TOKEN:
        required: true
    outputs:
      previous_run:
        description: "Previous successful run data for the component"
        value: ${{ jobs.manage-status.outputs.previous_run }}
      status_data:
        description: "Complete status data from gist"
        value: ${{ jobs.manage-status.outputs.status_data }}

jobs:
  manage-status:
    runs-on: ubuntu-latest
    outputs:
      previous_run: ${{ steps.status.outputs.previous_run }}
      status_data: ${{ steps.status.outputs.status_data }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: .github/workflow-scripts/package.json

      - name: Install dependencies
        working-directory: .github/workflow-scripts
        run: npm ci

      - name: Process status
        id: status
        working-directory: .github/workflow-scripts
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ inputs.gist_id }}
          ACTION: ${{ inputs.action }}
          COMPONENT_NAME: ${{ inputs.component_name }}
          COMPONENT_HASH: ${{ inputs.component_hash }}
          EXECUTION_PLAN: ${{ inputs.execution_plan }}
        run: npm run status 