name: E2E Tests

on:
  workflow_call:
    inputs:
      test_type:
        required: true
        type: string
        description: "Type of E2E test to run (mosaic-tile, mosaic-vending, or full)"
      needs_run:
        required: true
        type: string
        description: "Whether this workflow needs to run ('true' or 'false')"

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check if job needs to run
        id: check
        run: |
          if [[ "${{ inputs.needs_run }}" != "true" ]]; then
            echo "Job can be skipped - reusing previous successful run"
            exit 0
          fi

      - uses: actions/checkout@v3
      - name: Run E2E tests
        run: |
          echo "Running ${{ inputs.test_type }} E2E tests..."
          # Add actual E2E test commands here 