name: E2E Tests

on:
  workflow_call:
    inputs:
      test_type:
        required: true
        type: string
        description: "Type of E2E test to run (mosaic-tile, mosaic-vending, or full)"
      needs_run:
        required: true
        type: string
        description: "Whether this workflow needs to run ('true' or 'false')"
    outputs:
      e2e_result:
        description: "Result of the E2E test job"
        value: ${{ jobs.e2e.outputs.result }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}
    steps:
      - name: Check if job needs to run
        id: check
        run: |
          if [[ "${{ inputs.needs_run }}" != "true" ]]; then
            echo "Job can be skipped - reusing previous successful run"
            echo "result=skipped" >> $GITHUB_OUTPUT
            exit 0
          fi

      - uses: actions/checkout@v3
        if: steps.check.outputs.result != 'skipped'

      - name: Run E2E tests
        if: steps.check.outputs.result != 'skipped'
        run: |
          echo "Running ${{ inputs.test_type }} E2E tests..."
          # Add actual E2E test commands here

      - name: Set result
        id: set-result
        if: always()
        run: |
          if [[ "${{ inputs.needs_run }}" != "true" ]]; then
            echo "result=skipped" >> $GITHUB_OUTPUT
          else
            echo "result=${{ job.status }}" >> $GITHUB_OUTPUT
          fi