name: Generate Execution Plan

on:
  workflow_call:
    inputs:
      gist_id:
        required: true
        type: string
    secrets:
      GIST_TOKEN:
        required: true
    outputs:
      plan:
        description: "Complete execution plan for all jobs"
        value: ${{ jobs.create-plan.outputs.plan }}

permissions:
  contents: read
  actions: read
  gists: write

jobs:
  create-plan:
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.plan.outputs.plan }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: .github/workflow-scripts/package.json

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            .github/workflow-scripts/node_modules
          key: node-modules-${{ hashFiles('.github/workflow-scripts/package-lock.json') }}
          restore-keys: |
            node-modules-

      # Cache gist data between runs
      - name: Cache gist data
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/gist-data
          key: gist-data-${{ inputs.gist_id }}-${{ github.sha }}
          restore-keys: |
            gist-data-${{ inputs.gist_id }}-
            gist-data-

      - name: Install dependencies
        working-directory: .github/workflow-scripts
        run: npm ci

      - name: Generate execution plan
        id: plan
        working-directory: .github/workflow-scripts
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ inputs.gist_id }}
          GITHUB_TOKEN: ${{ github.token }}
          RUNNER_TEMP: ${{ runner.temp }}
          CACHE_PATH: ~/.cache/gist-data
        run: npm run execution-plan

      - name: Upload execution plan
        uses: actions/upload-artifact@v3
        with:
          name: execution-plan
          path: execution_plan.json
          retention-days: 1  # Only keep for 1 day since it's just for debugging