name: Changes Detection

on:
  workflow_call:
    outputs:
      frontend_needs_run:
        description: "Whether frontend CI needs to run"
        value: ${{ jobs.check-needs-run.outputs.frontend_needs_run }}
      mosaic_tile_needs_run:
        description: "Whether mosaic-tile CI needs to run"
        value: ${{ jobs.check-needs-run.outputs.mosaic_tile_needs_run }}
      mosaic_vending_needs_run:
        description: "Whether mosaic-vending CI needs to run"
        value: ${{ jobs.check-needs-run.outputs.mosaic_vending_needs_run }}
      full_e2e_needs_run:
        description: "Whether full E2E tests need to run"
        value: ${{ jobs.check-needs-run.outputs.full_e2e_needs_run }}

jobs:
  check-files-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      mosaic_tile: ${{ steps.filter.outputs.mosaic_tile }}
      mosaic_vending: ${{ steps.filter.outputs.mosaic_vending }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            mosaic_tile:
              - 'contracts/mosaic-tile-nft/**'
              - 'contracts/Cargo.toml'
            mosaic_vending:
              - 'contracts/mosaic-vending-minter/**'
              - 'contracts/Cargo.toml'

  check-needs-run:
    needs: check-files-changes
    runs-on: ubuntu-latest
    permissions:
      actions: read
    outputs:
      frontend_needs_run: ${{ steps.check-runs.outputs.frontend_needs_run }}
      mosaic_tile_needs_run: ${{ steps.check-runs.outputs.mosaic_tile_needs_run }}
      mosaic_vending_needs_run: ${{ steps.check-runs.outputs.mosaic_vending_needs_run }}
      full_e2e_needs_run: ${{ steps.check-runs.outputs.full_e2e_needs_run }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to get all history

      - name: Check if jobs need to run
        id: check-runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Function to check if a job needs to run
          check_job_needs_run() {
            local job_name=$1
            local files_changed=$2
            local code_path=$3
            
            # If files changed, we need to run
            if [[ "$files_changed" == "true" ]]; then
              echo "true"
              return
            fi
            
            # No files changed, check previous run status
            local last_run=$(gh run list --workflow pixel-canvas.yml \
              --json conclusion,jobs,headSha \
              --jq ".[] | select(.jobs[].name == \"$job_name\") | {conclusion: .conclusion, sha: .headSha}" \
              --limit 1)
            
            if [[ -n "$last_run" ]]; then
              local conclusion=$(echo "$last_run" | jq -r '.conclusion')
              if [[ "$conclusion" == "success" ]]; then
                echo "false"  # Previous run succeeded, no need to run
              else
                echo "true"   # Previous run failed, need to run
              fi
            else
              echo "true"     # No previous run found, need to run
            fi
          }
          
          # Check each job
          echo "frontend_needs_run=$(check_job_needs_run "frontend-ci" "${{ needs.check-files-changes.outputs.frontend }}" "frontend")" >> $GITHUB_OUTPUT
          echo "mosaic_tile_needs_run=$(check_job_needs_run "mosaic-tile-ci" "${{ needs.check-files-changes.outputs.mosaic_tile }}" "contracts/mosaic-tile-nft")" >> $GITHUB_OUTPUT
          echo "mosaic_vending_needs_run=$(check_job_needs_run "mosaic-vending-ci" "${{ needs.check-files-changes.outputs.mosaic_vending }}" "contracts/mosaic-vending-minter")" >> $GITHUB_OUTPUT
          
          # Full E2E needs to run if any component changed
          if [[ "${{ needs.check-files-changes.outputs.frontend }}" == "true" || \
                "${{ needs.check-files-changes.outputs.mosaic_tile }}" == "true" || \
                "${{ needs.check-files-changes.outputs.mosaic_vending }}" == "true" ]]; then
            echo "full_e2e_needs_run=true" >> $GITHUB_OUTPUT
          else
            echo "full_e2e_needs_run=false" >> $GITHUB_OUTPUT
          fi 