name: Setup Starsd

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: "Branch of Stargaze repository to build from"
        required: false
        default: "main"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Stargaze Repository
        uses: actions/checkout@v3
        with:
          repository: public-awesome/stargaze
          ref: ${{ inputs.branch }}
          path: stargaze

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('stargaze/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Build starsd
        working-directory: stargaze
        run: |
          make install
          echo "PATH=$PATH:$HOME/go/bin" >> $GITHUB_ENV 