name: Update Account Balances

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '* * * * *'  # Run every minute

jobs:
  update-balances:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install @cosmjs/cosmwasm-stargate node-fetch

      - name: Debug environment
        run: |
          echo "Debug: Checking environment variables"
          echo "Has GIST_ID: ${{ vars.GIST_ID != '' }}"
          echo "Has GIST_SECRET: ${{ secrets.GIST_SECRET != '' }}"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"

      - name: Update balances
        env:
          GIST_ID: ${{ vars.GIST_ID }}
          GIST_SECRET: ${{ secrets.GIST_SECRET }}
        run: |
          echo "Debug: Running update-balances.js"
          node scripts/update-balances.js