name: Update Account Balances

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '* * * * *'  # Run every minute

jobs:
  update-balances:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: .github/workflow-scripts/package.json

      - name: Install dependencies
        working-directory: .github/workflow-scripts
        run: npm install

      - name: Debug environment
        run: |
          echo "Debug: Checking environment variables"
          echo "Has GIST_ID (execution plan): ${{ vars.GIST_ID != '' }}"
          echo "Has PROJECT_GIST_ID (balances): ${{ vars.PROJECT_GIST_ID != '' }}"
          echo "Has GIST_SECRET: ${{ secrets.GIST_SECRET != '' }}"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"

      - name: Update balances
        working-directory: .github/workflow-scripts
        env:
          GIST_ID: ${{ vars.GIST_ID }}
          PROJECT_GIST_ID: ${{ vars.PROJECT_GIST_ID }}
          GIST_SECRET: ${{ secrets.GIST_SECRET }}
        run: |
          echo "Debug: Running update-balances script"
          echo "Debug: Using execution plan gist: $GIST_ID"
          echo "Debug: Using balance badges gist: $PROJECT_GIST_ID"
          npm run update-balances